### ISSUE TITLE
Document data upload workflow

### ISSUE THREAD

**Issue by bendichter** [dandi/roadmap#1]
This is non-trivial to get right in a way that is easy to use and can handle large data files. I have been working with figshare, which I think is currently the best UX for open data. They have a drag-and-drop interface on their webpage:
![image](https://user-images.githubusercontent.com/844306/63102392-0b9f0700-bf49-11e9-86cf-d82c022b2e3d.png)

and a cross-platform stand-alone app for uploading data:
![image](https://user-images.githubusercontent.com/844306/63102413-19548c80-bf49-11e9-8cb5-849339f2b65f.png)

But I guess our first step will probably be supporting an API. What language will this be in?

**Comment by yarikoptic** [comment]
Never used figshare's web ui for upload -- only `datalad export-to-figshare` ;)  Their case migth also be a bit simpler since figshare
- supports only flat list of files
- doesn't really care about incremental updates to existing datasets
- probably doesn't deal with that large uploads (in terms of size and # of files)

there might already be a web UI uploader for girder (e.g. https://github.com/girder/girder_web_components/blob/master/src/components/Upload.vue), and if not -- we could possible (ab)use the one openneuro developed for their platform: https://github.com/OpenNeuroOrg/openneuro/tree/b37c24e1156604966e870a4f6a0a25ecc9cf765a/packages/openneuro-app/src/scripts/uploader

**Comment by satra** [comment]
the intent would be NWB conversion and validation locally, with the upload being limited to validated NWB datasets. the standalone app will be necessary to handle file sizes beyond a certain size.

**Comment by yarikoptic** [comment]
> the standalone app will be necessary to handle file sizes beyond a certain size.

could you elaborate on that ? (file size limitations imposed by girder/aws/filesystem...? or just robustness/incremental upload etc issues?)

**Comment by satra** [comment]
> could you elaborate on that ?

many browsers have built-in limitations per file. https://www.smartfile.com/blog/file-size-limits-for-uploads-through-web-browsers/

**Comment by satra** [comment]
this is now superseded by other things.
